source: directed-abilene-zhang-5min-over-6months-ALL
result_trace_filename: trace_0_5000_pop0_chrate5_scale00004.csv  # default  = f'{directory}_{_from}-{to}_trace.csv'
intermediate_result_filename: directed-abilene-zhang-5min-over-6months-ALL_0-None_intermediate.csv  # default  = result_trace_filename + "_intermediate
_from: 0 # default 0
to: 5000  # default None, means slice is [_from:]
node_name_map: abilene_node_name_map.yaml  # default None, means leave the names
run_duration: 100  # default 100
scale_factor: 0.0004  # default 0.001
squash_rate: 1  # no effect if == 1
change_rate: 5  # default 2
ingress_nodes:  # default None, means choose all nodes
 - pop0
plot_figsize:
  - 20
  - 10
